# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

executors:
  windows-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:    
  unit-test:
    executor: windows-executor
    steps:
      - checkout

      - run:
          name: Restore NuGet Packages
          command: nuget restore YourSolution.sln

      - run:
          name: Build
          command: dotnet build NRhinoGenerator.sln /p:Configuration=Release

      - run:
          name: Run Tests
          command: |
            # Change the path and command according to your test project
            cd NRhinoGenerator
            dotnet test tests/Tests/Tests.csproj


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  unit-test-workflow:
    jobs:
      - unit-test
