# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# The Windows orb gives you everything you
# need to start using the Windows executor.
orbs:
  rhino: crashcloud/rhino@0.2.0


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:    
  unit-test:
    machine:
      image: 'windows-server-2022-gui:current'
      resource_class: windows.medium
      shell: powershell.exe -ExecutionPolicy Bypass

    steps:
      - checkout

      - run:
          name: Restore NuGet Packages
          command: nuget restore NRhinoGenerator.sln

      - run:
          name: Build
          command: dotnet build NRhinoGenerator.sln /p:Configuration=Release

      - run:
          name: Run Tests
          command: |
            # Change the path and command according to your test project
            cd NRhinoGenerator
            dotnet test tests/Tests/Tests.csproj


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  unit-test:
    jobs:
      - rhino/setup_rhino
