---
    name: deploy-nuget
    on:
      push:
        branches:
          - main
        paths:
            - '.github/workflows/deploy-nuget.yml'
            - 'src/*.csproj'
    
    jobs:
        build:
            runs-on: ubuntu-latest
            steps:
            - uses: actions/checkout@v3
        
            - name: Setup NuGet
              uses: NuGet/setup-nuget@v1
            
            - name: Restore Packages
              run: nuget restore
        
            - uses: actions/setup-dotnet@v3
              with:
                dotnet-version: |
                  7.0
            
            - name: Build & Publish Nuget
              id: publish_nuget
              run: |
                dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/crashcloud/index.json"
                dotnet nuget disable source 'nuget.org'
    
                dotnet build src/*.csproj --configuration Release --no-restore
                dotnet pack src/*.csproj --configuration Release --no-build --no-restore -o ./artifacts
                dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"        